# Site settings
title: MRE Melbourne
description: MRE ration recipies made from Melbourne products you could by from your local grocery store.
baseurl: "/portfolio"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
collections:
  pages:
    output: true
    permalink: /:name
  work:
    output: true
    permalink: /:name
